name: Check and build

on:
  push:
  pull_request:

concurrency:
  group: check-and-build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run format:check
      - run: npm run depcruise
      - run: npm run test
      - run: npm run build
